precompile erc 721 only owner_of
freeverseio/laos-ownership-node pull request #104
Opened 2023-08-03 15:41 UTC by asiniscalchi

2023-08-07 15:51 UTC, tonimateos requested changes
Minor comments, plus the View function requirement

2023-08-08 10:18 UTC, asiniscalchi commented on pallets/living-assets-ownership/src/functions.rs
> +pub fn convert_asset_id_to_owner(value: U256) -> H160 {
it will be renamed when transfer of assets will be activated.

2023-08-08 10:19 UTC, asiniscalchi commented on precompile/erc721/contracts/IERC721.sol
> +    function tokenURI(uint256 tokenId) external view returns (string memory);
sgtm

2023-08-08 10:20 UTC, asiniscalchi commented on precompile/erc721/src/lib.rs
> +			Action::TockenURI => FunctionModifier::NonPayable,
sgtm

2023-08-08 10:31 UTC, asiniscalchi commented on precompile/erc721/src/tests.rs
> +	/// * `$name`: An identifier to name the precompile mock type.
sgtm

2023-08-08 10:57 UTC, asiniscalchi commented on pallets/living-assets-ownership/src/traits.rs
> +
sgtm

2023-08-08 10:57 UTC, asiniscalchi commented on pallets/living-assets-ownership/Cargo.toml
> +sp-core = { workspace = true }
sgtm

2023-08-08 12:49 UTC, asiniscalchi commented on pallets/living-assets-ownership/src/traits.rs
> +	fn owner_of(collection_id: CollectionId, asset_id: U256) -> Result<H160, &'static str>;
yes totally agree.

2023-08-08 13:00 UTC, asiniscalchi commented on precompile/living-assets/src/tests.rs
> +		hex::decode("fb24ae530000000000000000000000000000000000000000000000000000000000000000")
I've noticed that this value is used only once in the test. While I understand the importance of constants for frequently used values, would it be necessary in this case where it's a one-time use?

2023-08-08 13:04 UTC, asiniscalchi commented on pallets/living-assets-ownership/src/lib.rs
> +pub fn collection_id_to_address(collection_id: CollectionId) -> H160 {
it'll be adressed : https://github.com/freeverseio/laos-ownership-node/pull/116

2023-08-08 13:05 UTC, asiniscalchi commented on pallets/living-assets-ownership/src/traits.rs
> +	fn owner_of(collection_id: CollectionId, asset_id: U256) -> Result<H160, &'static str>;
it will be addressed here : https://github.com/freeverseio/laos-ownership-node/pull/116

2023-08-08 13:05 UTC, asiniscalchi commented on pallets/living-assets-ownership/src/traits.rs
> +	fn owner_of(collection_id: CollectionId, asset_id: U256) -> Result<H160, &'static str>;
https://github.com/freeverseio/laos-ownership-node/pull/116

2023-08-08 13:06 UTC, tonimateos commented on precompile/living-assets/src/tests.rs
> +	let unexistent_selector =
minor: unexistent --> nonexistent

2023-08-08 13:20 UTC, merged