Add evochain light client
freeverseio/laos-ownership-node pull request #108
Opened 2023-08-04 11:02 UTC by dastanfv

## Runtime

### Evochain light client

Adds `evochain` light client, i.e adds `pallet_bridge_grandpa` pallet with `type TargetChain = Evochain`

### Extract primitives

Similar to this [PR](https://github.com/freeverseio/laos-evolution-node/pull/51), it decouples primitives from runtime and creates a separate crate `bp-ownership-parachain` 

### Adds `EvochainFinalityApi` impl

This is auto-generated Runtime API that is used by `laos-relay`

2023-08-08 06:55 UTC, tonimateos approved these changes

2023-08-28 08:41 UTC, dastanfv commented
probably needs to be merged after changes to `parity-bridges-common` are merged

2023-08-29 09:29 UTC, asiniscalchi requested changes

2023-08-29 09:37 UTC, dastanfv commented on Cargo.toml
> +node-template-runtime = { git = "https://github.com/freeverseio/laos-evolution-node.git", branch = "dev" }
yes, good catch, it was not needed. I removed it

2023-08-29 09:53 UTC, asiniscalchi approved these changes
little comment

2023-08-29 09:53 UTC, asiniscalchi commented on runtime/src/xcm_config.rs
> +	type IsTeleporter = NativeAsset; // Teleporting is disabled.
It seems it is enabled now

2023-08-29 10:04 UTC, dastanfv commented
should be merged after https://github.com/freeverseio/parity-bridges-common/pull/6

2023-08-29 10:07 UTC, merged